providers:
  - id: provider-a
    name: Provider A
    host: https://provider-a.com
    features:
      - apps
      - pipelines
  - id: provider-b
    name: Provider B
    host: https://provider-b.com
    features:
      - groups
