{{ if .Values.providers.cloudfoundry.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dyve.fullname" . }}-cloudfoundry
  labels:
{{ include "dyve.labels" . | indent 4 }}
spec:
  selector:
    dyve: provider-cloudfoundry
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
 {{- end }}