{{ if .Values.providers.cloudfoundry.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dyve.fullname" . }}-provider-cloudfoundry
  labels:
{{ include "dyve.labels" . | indent 4 }}
data:
  config.yaml: >
  {{- if .Values.providers.cloudfoundry.fullConfig}}
{{ .Values.providers.cloudfoundry.fullConfig | toYaml | toString | indent 4 }}
  {{else}}
{{ .Values.providers.cloudfoundry.config | toYaml | toString | indent 4 }}
  {{end}}
{{end}}