name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/pages.yml
      - infra/helm/**
      - docs/**

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Add Helm dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          for d in infra/helm/*/ ; do
              echo "$d"
              helm dependency update $d
          done
      - run: |
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
          args=(--owner "$owner" --repo "$repo")
          args+=(--charts-dir "infra/helm")
          args+=(--config ".github/files/cr.yaml")
          ".github/files/cr.sh" "${args[@]}"
        shell: bash
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - run: mv .cr-index/index.yaml docs/docs/index.yaml
      - run: pip install mkdocs-material
      - run: cd docs && mkdocs gh-deploy --force