name: Release Charts

on:
  push:
    branches:
      - main
    paths:
      - infra/helm/**

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Add Helm dependencies
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          for d in infra/helm/*/ ; do
              echo "$d"
              helm dependency update $d
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.2.1
        with:
          charts_dir: infra/helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"